# Generated by Django 5.0.4 on 2024-04-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
